### ISSUE TITLE
Please consider adding an example that is not linked to some external library

### ISSUE THREAD

**Issue by veldtmana** [dhassaine/reduxless#77]
I'm considering using this library as a simple server-side caching model, however, your docs only provide examples where your store is being integrated into an external library such as preact or react (or other).

I've been looking at your docs and I would assume it would work something like this

```
const { List } = require('immutable');
const { createstore } = require('reduxless');

const store = createstore({
  fooList: List(['baz', 'quux'])
});

const foos = () => store.get('fooList');

store.set('fooList', foos.push('quux'));
````
However, that approach doesn't seem to work

**Comment by dhassaine** [comment]
Hi Alex, thanks for taking the time to file an issue. I've modified the library to export the raw functionality. So if you pull the latest release, you should be able to do this:
```
import { createStore, selectorMemoizer } from 'reduxless';

const store = createStore({ name: 'Djamel' });
const getName = store => store.get('name');
const memoizedGetName = selectorMemoizer(getName, name => 'Hi ' + name);
```

I'll add this to the documentation later.
